// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX9mXJxqRJAGZi5kLVFw653vHIwL37pFA',
    appId: '1:539621457709:web:f8cecaad66a20dfa4b9da4',
    messagingSenderId: '539621457709',
    projectId: 'personal-task-app',
    authDomain: 'personal-task-app.firebaseapp.com',
    storageBucket: 'personal-task-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzjlWz5Ju8gFiGVIawweoSYP1qW4ipMUY',
    appId: '1:539621457709:android:1c0c1ba3b4bd7c7b4b9da4',
    messagingSenderId: '539621457709',
    projectId: 'personal-task-app',
    storageBucket: 'personal-task-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWMPNOTi7haQi0g6tIcpButaSyWXM5bFs',
    appId: '1:539621457709:ios:3e7e797f961a82ca4b9da4',
    messagingSenderId: '539621457709',
    projectId: 'personal-task-app',
    storageBucket: 'personal-task-app.appspot.com',
    iosBundleId: 'com.example.productivityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWMPNOTi7haQi0g6tIcpButaSyWXM5bFs',
    appId: '1:539621457709:ios:5352cd7c49cbf53a4b9da4',
    messagingSenderId: '539621457709',
    projectId: 'personal-task-app',
    storageBucket: 'personal-task-app.appspot.com',
    iosBundleId: 'com.example.productivityApp.RunnerTests',
  );
}
